# Generated by Django 5.2.6 on 2025-09-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(db_index=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_name'],
                'indexes': [models.Index(fields=['normalized_name'], name='products_pr_normali_47cae9_idx'), models.Index(fields=['brand', 'model'], name='products_pr_brand_3f94b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_product_id', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.store')),
            ],
            options={
                'ordering': ['current_price'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['query'], name='products_se_query_667183_idx'), models.Index(fields=['searched_at'], name='products_se_searche_19b9c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productlisting')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['listing', 'recorded_at'], name='products_pr_listing_d837f4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['store', 'is_available'], name='products_pr_store_i_739a51_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['current_price'], name='products_pr_current_8504dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together={('product', 'store')},
        ),
    ]
